
classes:
# ----------------------------------------------------------------------------
- name: "y2b_h2tau"
  label: "Y(bb)H($\\tau\\tau$)"
  file_basenames:
  - "2024__mt__mt_base_sr__xyh_y2b_h2tau__Nominal"
  is_signal: true
# ----------------------------------------------------------------------------
- name: "y2tau_h2b"
  label: "Y(bb)H($\\tau\\tau$)"
  file_basenames:
  - "2024__mt__mt_base_sr__xyh_y2tau_h2b__Nominal"
  is_signal: true
# ----------------------------------------------------------------------------
- name: "t"
  label: "t+X"
  file_basenames:
  - "2024__mt__mt_base_sr__single_t__Nominal"
  is_signal: false
# ----------------------------------------------------------------------------
- name: "tt"
  label: "tX and t$\\bar{t}$"
  file_basenames:
  - "2024__mt__mt_base_sr__tt_rem__Nominal"
  - "2024__mt__mt_base_sr__tt_tautau__Nominal"
  - "2024__mt__mt_base_sr__single_t__Nominal"
  is_signal: false
# ----------------------------------------------------------------------------
- name: "z"
  label: "Z($\\ell\\ell$)"
  file_basenames:
  - "2024__mt__mt_base_sr__dy_fakes__Nominal"
  - "2024__mt__mt_base_sr__dy_tautau__Nominal"
  is_signal: false
# ----------------------------------------------------------------------------
- name: "jetfakes_mc"
  label: "j $\\to \\tau_{\\text{h}}"
  file_basenames:
  - "2024__mt__mt_base_sr__tt_jetfakes__Nominal"
  - "2024__mt__mt_base_sr__w_lnu__Nominal"
  is_signal: false
# ----------------------------------------------------------------------------
- name: "single_h"
  label: "Single H"
  file_basenames:
  - "2024__mt__mt_base_sr__single_h__Nominal"
  is_signal: false
# ----------------------------------------------------------------------------
- name: "diboson"
  label: "Diboson"
  file_basenames:
  - "2024__mt__mt_base_sr__diboson__Nominal"
  is_signal: false
