# -----------------------------------------------------------------------------
# Data source
# -----------------------------------------------------------------------------

data_source:
  base_dir: /ceph/mmolch/xyh-bbtautau-crown/bbtautau/data/output/TrainingDataFrames/shapes-2026-06-10/2024/mt_base_sr
  channel: mt

# -----------------------------------------------------------------------------
# Input variables
# -----------------------------------------------------------------------------

input_variables:
# -----------------------------------------------------------------------------
- name: "n_jets"
  transformation: "none"
# -----------------------------------------------------------------------------
- name: "n_bjets"
  transformation: "none"
# -----------------------------------------------------------------------------
- name: "pt_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "pt_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "eta_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "eta_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "phi_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "phi_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "m_vis"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "pt_vis"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "deltaR_ditaupair"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_pt_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_pt_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_eta_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_eta_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_phi_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_phi_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_btag_value_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_btag_value_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_m_inv"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_pt_dijet"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "bpair_deltaR"
  transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jpt_1"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jpt_2"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jeta_1"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jeta_2"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jphi_1"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jphi_2"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jtag_value_1"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "jtag_value_2"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "mjj"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "pt_dijet"
#   transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "met"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "metphi"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "mt_1"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "mt_2"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "mt_tot"
  transformation: "z_score"
# -----------------------------------------------------------------------------
# - name: "mass_tautaubb"
#   transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "pt_tautaubb"
  transformation: "z_score"
# -----------------------------------------------------------------------------
- name: "pt_tautau"
  transformation: "z_score"
# -----------------------------------------------------------------------------
# - name: "m_fastmtt"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "pt_fastmtt"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "eta_fastmtt"
#   transformation: "z_score"
# # -----------------------------------------------------------------------------
# - name: "phi_fastmtt"
#   transformation: "z_score"


# -----------------------------------------------------------------------------
# Input parameters (PNN)
# -----------------------------------------------------------------------------

input_parameters:
# ----------------------------------------------------------------------------
- name: "m_x"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "m_y"
  transformation: "z_score"

# -----------------------------------------------------------------------------
# Process classes
# -----------------------------------------------------------------------------

output_classes:
# -----------------------------------------------------------------------------
- name: "xyh_y2b_h2tau"
  label: "Y(bb)H($\\tau\\tau$)"
  file_basenames:
  - "2024__mt__mt_base_sr__xyh_y2b_h2tau__Nominal"
  is_signal: true
# -----------------------------------------------------------------------------
- name: "xyh_y2tau_h2b"
  label: "Y(bb)H($\\tau\\tau$)"
  file_basenames:
  - "2024__mt__mt_base_sr__xyh_y2tau_h2b__Nominal"
  is_signal: true
# -----------------------------------------------------------------------------
- name: "t"
  label: "Single t"
  file_basenames:
  - "2024__mt__mt_base_sr__single_t__Nominal"
  is_signal: false
# -----------------------------------------------------------------------------
- name: "tt"
  label: "t$\\bar{t}$"
  file_basenames:
  - "2024__mt__mt_base_sr__tt_rem__Nominal"
  - "2024__mt__mt_base_sr__tt_tautau__Nominal"
  is_signal: false
# -----------------------------------------------------------------------------
- name: "z"
  label: "Z($\\tau\\tau$)"
  file_basenames:
  - "2024__mt__mt_base_sr__dy_tautau__Nominal"
  is_signal: false
# -----------------------------------------------------------------------------
- name: "jetfakes"
  label: "$\\text{j} \\to \\tau_{\\text{h}}$"
  file_basenames:
  - "2024__mt__mt_base_sr__jetfakes__tau_antiid_vs_jet"
  is_signal: false
# -----------------------------------------------------------------------------
- name: "single_h"
  label: "Single H"
  file_basenames:
  - "2024__mt__mt_base_sr__single_h__Nominal"
  is_signal: false
# -----------------------------------------------------------------------------
- name: "diboson"
  label: "Diboson"
  file_basenames:
  - "2024__mt__mt_base_sr__vv__Nominal"
  is_signal: false