variables:
# ----------------------------------------------------------------------------
- name: "n_jets"
  transformation: "none"
# ----------------------------------------------------------------------------
- name: "n_bjets"
  transformation: "none"
# ----------------------------------------------------------------------------
- name: "pt_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "pt_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "eta_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "eta_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "phi_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "phi_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "m_vis"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "pt_vis"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "deltaR_ditaupair"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_pt_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_pt_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_eta_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_eta_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_phi_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_phi_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_btag_value_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_btag_value_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_m_inv"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_pt_dijet"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "bpair_deltaR"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jpt_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jpt_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jeta_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jeta_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jphi_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jphi_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jtag_value_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "jtag_value_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "mjj"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "pt_dijet"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "met"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "metphi"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "metSumEt"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "mt_1"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "mt_2"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "mt_tot"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "mass_tautaubb"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "pt_tautaubb"
  transformation: "z_score"
# ----------------------------------------------------------------------------
- name: "pt_tautau"
  transformation: "z_score"

parameters:
# ----------------------------------------------------------------------------
- name: "m_x"
  transformation: "one_hot_encoding"
# ----------------------------------------------------------------------------
- name: "m_y"
  transformation: "one_hot_encoding"
