# -----------------------------------------------------------------------------
# Hidden layers
# -----------------------------------------------------------------------------

hidden_layers:
# ----------------------------------------------------------------------------
- size: 256
  activation: "elu"
  norm: "batch_norm_1d"
  dropout: "none"
# ----------------------------------------------------------------------------
- size: 256
  activation: "elu"
  norm: "batch_norm_1d"
  dropout: "none"
# ----------------------------------------------------------------------------
- size: 256
  activation: "elu"
  norm: "batch_norm_1d"
  dropout: "none"

# -----------------------------------------------------------------------------
# Output layer
# -----------------------------------------------------------------------------

output_layer:
  activation: "none"

# -----------------------------------------------------------------------------
# Batch configuration
# -----------------------------------------------------------------------------

batch_and_epochs:
  max_epochs: 1000
  batch_size: 32768

# -----------------------------------------------------------------------------
# Optimizer
# -----------------------------------------------------------------------------

optimizer:
  class_name: torch.optim.Adam
  kwargs:
    lr: 5.0e-4
    weight_decay: 1.0e-4
  gradient_clip_val: 10.0

# -----------------------------------------------------------------------------
# Loss
# -----------------------------------------------------------------------------

loss:
  fn_name: xyh_ml.models.losses.weighted_cross_entropy_loss
  kwargs: {}

# -----------------------------------------------------------------------------
# Callbacks
# -----------------------------------------------------------------------------

early_stopping:
  patience: 20
  min_delta: 0.005